name: 'Go release'
description: 'Releases a go project using goreleaser'
author: 'Niklas Gergs'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
    - name: Test
      shell: bash
      run: go test -race ./...
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: latest
        install-mode: binary
        args: --timeout=10m
        Skip-cache: true
