name: 'Go release'
description: 'Releases a go project using goreleaser'
author: 'Niklas Gergs'
inputs:
  go-version:
    description: >-
      The go-version that should be used to run the tests.
      SemVer version range syntax is supported.
    required: true
  github-token:
    description: Github token to perform the release.
    required: true
  dockerhub-username:
    description: The username for dockerhub
    required: true
  dockerhub-password:
    description: The password for dockerhub
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      shell: bash
      run: go test -race ./...
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        install-mode: binary
        args: --timeout=10m
        Skip-cache: true