name: 'Go tests'
description: 'Runs tests using go test ./... for the given go projects'
author: 'Niklas Gergs'
inputs:
  go-version:
    description: >-
      The go-version that should be used to run the tests.
      SemVer's version range syntax is supported.
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Cache go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Test
      run: go test ./...
