name: 'Go tests'
description: 'Runs tests using go test ./... for the given go projects'
author: 'Niklas Gergs'
inputs:
  go-version:
    description: >-
      The go-version that should be used to run the tests.
      SemVer version range syntax is supported.
    required: true
  github-token:
    description: Github token to perform the release.
    required: true
  dockerhub-username:
    description: The username for dockerhub
    required: true
  dockerhub-password:
    description: The password for dockerhub
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
    - name: Prepare licenses
      shell: bash
      run: |
        go install github.com/google/go-licenses@latest && \
        $(go env GOPATH)/bin/go-licenses save ./... --save_path=legal
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-password }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}