name: 'Release docker'
description: 'Builds a dockerfile and releases it to DockerHub with a corresponding GitHub Release from softprops/action-gh-release@v1. Also pushes to latest.'
author: 'Niklas Gergs'
inputs:
  github-token:
    description: Github token to perform the release.
    required: true
  docker-image-name:
    description: The image name of the docker container that will be pushed.
    required: true
  dockerhub-username:
    description: The username for dockerhub
    required: true
  dockerhub-password:
    description: The password for dockerhub
    required: true
  release-version:
    description: The version of the release
    required: true
  release-notes-cache-key:
    description: Cache key for actions/cache@v3 to load the release notes from the changelog.txt entry.
    required: true
  git-checkout:
    description: Wether to check out code from git. If you specify false, you ar required to checkout the code beforehand!
    required: false
    default: true
  dockerfile:
    description: Dockerfile to use for building the image
    required: false
    default: "./Dockerfile"
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      if: ${{ inputs.git-checkout == 'true' }}
    - name: Load release notes
      uses: actions/cache@v3
      id: cache-release-notes
      with:
        path: changelog.txt
        key: ${{ inputs.release-notes-cache-key }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-password }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Docker push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        push: true
        build-args: VERSION=v${{ inputs.release-version }}
        tags: |
          ${{ inputs.dockerhub-username }}/${{ inputs.docker-image-name }}:${{ inputs.release-version }}
          ${{ inputs.dockerhub-username }}/${{ inputs.docker-image-name }}:latest
    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ inputs.release-version }}
        body_path: changelog.txt
        token: ${{ inputs.github-token }}
